INSERT INTO games(~) VALUES ("?"); 
CREATE TABLE IF NOT EXISTS games2 AS SELECT * FROM (SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY CASE WHEN rowid IS NULL THEN 1 ELSE 0 END) AS rownumber,* FROM games) as t1 INNER JOIN (SELECT ROW_NUMBER() OVER(ORDER BY CASE WHEN ~ IS NULL THEN 1 ELSE 0 END) AS rownumber2,~ AS ~2 FROM games) as t2 ON t1.rownumber = t2.rownumber2);
UPDATE games2 SET ~=~2;
ALTER TABLE games2 DROP COLUMN ~2;
ALTER TABLE games2 DROP COLUMN rownumber;
ALTER TABLE games2 DROP COLUMN rownumber2;
DELETE FROM games;
INSERT INTO games SELECT * FROM games2;
DROP TABLE games2;
UPDATE games SET ~ = NULL WHERE EXISTS (SELECT * FROM games AS t2 WHERE games.~ = t2.~ and games.rowid > t2.rowid);
DELETE FROM games WHERE ~ IS NULL AND rowid = (SELECT MAX(rowid) FROM games);
UPDATE sqlite_sequence SET seq = (SELECT MAX(rowid) FROM games) WHERE name="games";