# Generated by Django 3.2.9 on 2021-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
